### PR TITLE
Rewrite cpu-screen in Perl, drop other scripts

### PR DESCRIPTION
**Pull request by zeha**

### CODE REVIEW

**Comment by jkirk** [comment]
Just tested your perl script implemtation of `ip-screen`:

```
❯ time bin/ip-screen
 | 10.17.0.209 |  |  | 10.10.2.100 | 10.17.0.128
bin/ip-screen  0,02s user 0,00s system 97% cpu 0,025 total
```

vs the original binary:
```
❯ time ./ip-screen
10.17.0.209 | 10.10.2.100 | 10.17.0.128
./ip-screen  0,00s user 0,00s system 60% cpu 0,001 total
```
Another option I just came up with:
```
❯ time hostname -I | sed -e 's/ [^ ]*:.*$//' -e 's/ / | /g' 
10.17.0.209 | 10.10.2.100 | 10.17.0.128
hostname -I  0,00s user 0,00s system 78% cpu 0,003 total
sed -e 's/ [^ ]*:.*$//' -e 's/ / | /g'  0,00s user 0,00s system 83% cpu 0,005 total
```

(`hostname -I` omits the loopback IP, but shows the IPv6 addresses, which I tried to hide with this sed line...)

**Comment by zeha** [comment]
Thanks for checking. @jkirk could you paste the output of `ip a` of the system you used here?

**Comment by jkirk** [comment]
Here you are (or do you need the "normal" `ip a` output)?
```
❯ ip -4 -o addr show                   
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
4: wlp0s20f3    inet 10.17.0.209/24 brd 10.17.0.255 scope global dynamic noprefixroute wlp0s20f3\       valid_lft 25357sec preferred_lft 25357sec
69: wg-hetzner    inet 10.10.2.100/32 scope global noprefixroute wg-hetzner\       valid_lft forever preferred_lft forever
90: enx387c760de5fc    inet 10.17.0.128/24 brd 10.17.0.255 scope global dynamic noprefixroute enx387c760de5fc\       valid_lft 25253sec preferred_lft 25253sec
````

I also tried to benchmark the different implementations.
The original binary. (I compiled it locally, so your mileage may vary):
```
❯ time (for i in $(seq 1000); ./ip-screen > /dev/null)
( for i in $(seq 1000); do; ./ip-screen > /dev/null; done; )  0,28s user 0,23s system 103% cpu 0,492 total
```

Your Perl implementation:
```
❯ time (for i in $(seq 1000); ./ip-screen > /dev/null)
( for i in $(seq 1000); do; ./ip-screen > /dev/null; done; )  11,75s user 2,48s system 99% cpu 14,287 total
```

The hostname/sed implementation:
```
❯ time (for i in $(seq 1000); hostname -I | sed -e 's/ [^ ]*:.*$//' -e 's/ / | /g' > /dev/null)
( for i in $(seq 1000); do; hostname -I | sed -e 's/ [^ ]*:.*$//' -e  > ; done  1,29s user 0,66s system 136% cpu 1,430 total
```

So, the hostname/sed implementation is slower than the original C implementation. (If I calculate correctly, its about 1ms slower).
But the Perl implementation seems way slower (about 10ms slower), no? What do you think?

FYI, as I was not sure, if I am holding it right, I also tried calling hostname/sed via `sh -c` :
```
❯ time (for i in $(seq 1000); sh -c "hostname -I | sed -e 's/ [^ ]*:.*$//' -e 's/ / | /g'" > /dev/null)
( for i in $(seq 1000); do; sh -c  > /dev/null; done; )  1,47s user 0,40s system 127% cpu 1,475 total
```

FTR, I also made some other ip/awk/sed + ip/sed tests (which are slower than hostname/sed):

```
❯ time (for i in $(seq 1000); ip -4 -o addr show | sed -n 's/.*inet \([0-9\.]*\).*/\1/p' | sed ':a;N;$!ba;s/\n/ /g;s/ / | /g' > /dev/null)
( for i in $(seq 1000); do; command ip -color=auto -4 -o addr show | sed -n  )  2,48s user 1,41s system 178% cpu 2,174 total

❯ time (for i in $(seq 1000); ip -4 -o addr show | awk '{print $4}' | sed 's/\/.*//' | sed ':a;N;$!ba;s/\n/ /g;s/ / | /g;s/ *$//' > /dev/null)
( for i in $(seq 1000); do; command ip -color=auto -4 -o addr show | awk  |  )  2,99s user 1,59s system 208% cpu 2,194 total
```

**Comment by zeha** [comment]
> Here you are (or do you need the "normal" `ip a` output)?

I really did mean `ip a`.

> So, the hostname/sed implementation is slower than the original C implementation. (If I calculate correctly, its about 1ms slower). But the Perl implementation seems way slower (about 10ms slower), no? What do you think?

Maybe we just use `hostname -I` as is then?

**Comment by jkirk** [comment]
Haha, 

> > Here you are (or do you need the "normal" `ip a` output)?
> 
> I really did mean `ip a`.

Haha, thought so, but I was too lazy to anonymize my IPv6 addresses (due to lack of knowledge, which are publicly accessible / which ones need to be anonymized - I replace some random ffff and 0000).

```
❯ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: wwan0: <POINTOPOINT,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/none 
4: wlp0s20f3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether f4:3b:d8:a9:ff:ff brd ff:ff:ff:ff:ff:ff
    inet 10.17.0.209/24 brd 10.17.0.255 scope global dynamic noprefixroute wlp0s20f3
       valid_lft 42226sec preferred_lft 42226sec
    inet6 ffff:e8be:e67::136/128 scope global dynamic noprefixroute 
       valid_lft 42227sec preferred_lft 42227sec
    inet6 fd9d:e8be:e67:0:f63b:d8ff:ffff:f097/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::f63b:d8ff:ffff:f097/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
7: vboxnet0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 0a:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
8: vboxnet1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 0a:00:00:00:00:01 brd ff:ff:ff:ff:ff:ff
69: wg-hetzner: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.10.2.100/32 scope global noprefixroute wg-hetzner
       valid_lft forever preferred_lft forever
104: enx387c760de5fc: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 38:7c:76:0d:ff:ff brd ff:ff:ff:ff:ff:ff
    inet 10.17.0.128/24 brd 10.17.0.255 scope global dynamic noprefixroute enx387c760de5fc
       valid_lft 42231sec preferred_lft 42231sec
    inet6 fd9d:ffff:e67::c9d/128 scope global dynamic noprefixroute 
       valid_lft 42232sec preferred_lft 42232sec
    inet6 fd9d:ffff:e67:0:b243:df09:8cb0:bde5/64 scope global temporary dynamic 
       valid_lft 603832sec preferred_lft 85419sec
    inet6 fd9d:ffff:e67:0:3a7c:76ff:fe0d:e5fc/64 scope global mngtmpaddr noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::ffff:76ff:fe0d:e5fc/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

> > So, the hostname/sed implementation is slower than the original C implementation. (If I calculate correctly, its about 1ms slower). But the Perl implementation seems way slower (about 10ms slower), no? What do you think?
> 
> Maybe we just use `hostname -I` as is then?

Hmm, why not?

**Comment by jkirk** [comment]
JFTR, the correct hostname/sed line should look like this: `hostname -I | sed -e 's/ [^ ]*:.*$/ /;s/ / | /g;s/ | $//'`

(This line now also works correctly if no IPv6 exists).

**Comment by mika** [comment]
> JFTR, the correct hostname/sed line should look like this: `hostname -I | sed -e 's/ [^ ]*:.*$/ /;s/ / | /g;s/ | $//'`
> 
> (This line now also works correctly if no IPv6 exists).

Quite amazing find BTW, I wasn't aware that hostname had an option to list IP addresses :open_mouth: :+1:

**Comment by jkirk** [comment]
Hehe, me neither... Seems to be added  in v3.0.2 back in 2010: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=562830.

**Comment by zeha** [comment]
Decision was:
- lets go with hostname -I for livecd
- rewrite cpu-screen to perl
- drop everything else from here, as lesspipe.sh is unused by zshrc if lesspipe exists (which always exists on Debian)

**Pull request merged**
